version: '3'
services:
  influxdb:
    image: influxdb:latest
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - '8086:8086'
    env_file: .env
  # Displays the results in a Grafana dashborad
  grafana:
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning/
    env_file: .env
volumes:
  grafana:
  influxdb:
