{
 "title": "Placemon",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FFT",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"placemon_data\") \n|> range(start: -5m)\n|> filter(fn: (r) => r._measurement == \"Building 1\" and (r._field == \"000\"  or r._field == \"020\"  or r._field == \"040\"  or r._field == \"060\"  or r._field == \"080\"  or r._field == \"100\"  or r._field == \"120\"  or r._field == \"140\"  or r._field == \"160\"  or r._field == \"180\"  or r._field == \"200\"  or r._field == \"220\"  or r._field == \"240\"  or r._field == \"260\"  or r._field == \"280\"  or r._field == \"300\"  or r._field == \"320\"  or r._field == \"340\"  or r._field == \"360\"  or r._field == \"380\"  or r._field == \"400\"  or r._field == \"420\"  or r._field == \"440\"  or r._field == \"460\"  or r._field == \"480\"  or r._field == \"500\" ))"
    }
   ]
  },
  {
   "title": "Accelerometer X",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"placemon_data\") \n|> range(start: -1d)\n|> filter(fn: (r) => r._measurement == \"Building 1\" and r._field == \"Accelerometer X\")"
    }
   ]
  },
  {
   "title": "Accelerometer Y",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"placemon_data\") \n|> range(start: -1d)\n|> filter(fn: (r) => r._measurement == \"Building 1\" and r._field == \"Accelerometer Y\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"placemon_data\") \n|> range(start: -1d)\n|> filter(fn: (r) => r._measurement == \"Building 1\" and r._field == \"humidity\")\n"
    }
   ]
  },
  {
   "title": "Accelerometer Z",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"placemon_data\") \n|> range(start: -1d)\n|> filter(fn: (r) => r._measurement == \"Building 1\" and r._field == \"Accelerometer Z\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"placemon_data\") \n|> range(start: -1d)\n|> filter(fn: (r) => r._measurement == \"Building 1\" and r._field == \"temperature\")\n\n"
    }
   ]
  },
  {
   "title": "Magnetic X",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"placemon_data\") \n|> range(start: -1d)\n|> filter(fn: (r) => r._measurement == \"Building 1\" and r._field == \"Magnetic X\")"
    }
   ]
  },
  {
   "title": "Magnetic Y",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"placemon_data\") \n|> range(start: -1d)\n|> filter(fn: (r) => r._measurement == \"Building 1\" and r._field == \"Magnetic Y\")"
    }
   ]
  },
  {
   "title": "Magnetic Z",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"placemon_data\") \n|> range(start: -1d)\n|> filter(fn: (r) => r._measurement == \"Building 1\" and r._field == \"Magnetic Z\")"
    }
   ]
  }
 ]
}